var d3 = window && window.d3 || require("d3-selection");
var selection = d3.selection;
import {default as A} from "./selection/A";
  selection.prototype.A = A;
import {default as Abbr} from "./selection/Abbr";
  selection.prototype.Abbr = Abbr;
import {default as Accept} from "./selection/Accept";
  selection.prototype.Accept = Accept;
import {default as Accesskey} from "./selection/Accesskey";
  selection.prototype.Accesskey = Accesskey;
import {default as Action} from "./selection/Action";
  selection.prototype.Action = Action;
import {default as Address} from "./selection/Address";
  selection.prototype.Address = Address;
import {default as AlignContent} from "./selection/AlignContent";
  selection.prototype.AlignContent = AlignContent;
import {default as AlignItems} from "./selection/AlignItems";
  selection.prototype.AlignItems = AlignItems;
import {default as AlignSelf} from "./selection/AlignSelf";
  selection.prototype.AlignSelf = AlignSelf;
import {default as Alt} from "./selection/Alt";
  selection.prototype.Alt = Alt;
import {default as Area} from "./selection/Area";
  selection.prototype.Area = Area;
import {default as Article} from "./selection/Article";
  selection.prototype.Article = Article;
import {default as Aside} from "./selection/Aside";
  selection.prototype.Aside = Aside;
import {default as Audio} from "./selection/Audio";
  selection.prototype.Audio = Audio;
import {default as Autocomplete} from "./selection/Autocomplete";
  selection.prototype.Autocomplete = Autocomplete;
import {default as Autofocus} from "./selection/Autofocus";
  selection.prototype.Autofocus = Autofocus;
import {default as B} from "./selection/B";
  selection.prototype.B = B;
import {default as Background} from "./selection/Background";
  selection.prototype.Background = Background;
import {default as BackgroundAttachment} from "./selection/BackgroundAttachment";
  selection.prototype.BackgroundAttachment = BackgroundAttachment;
import {default as BackgroundBlendMode} from "./selection/BackgroundBlendMode";
  selection.prototype.BackgroundBlendMode = BackgroundBlendMode;
import {default as BackgroundClip} from "./selection/BackgroundClip";
  selection.prototype.BackgroundClip = BackgroundClip;
import {default as BackgroundColor} from "./selection/BackgroundColor";
  selection.prototype.BackgroundColor = BackgroundColor;
import {default as BackgroundImage} from "./selection/BackgroundImage";
  selection.prototype.BackgroundImage = BackgroundImage;
import {default as BackgroundOrigin} from "./selection/BackgroundOrigin";
  selection.prototype.BackgroundOrigin = BackgroundOrigin;
import {default as BackgroundPosition} from "./selection/BackgroundPosition";
  selection.prototype.BackgroundPosition = BackgroundPosition;
import {default as BackgroundRepeat} from "./selection/BackgroundRepeat";
  selection.prototype.BackgroundRepeat = BackgroundRepeat;
import {default as BackgroundSize} from "./selection/BackgroundSize";
  selection.prototype.BackgroundSize = BackgroundSize;
import {default as Base} from "./selection/Base";
  selection.prototype.Base = Base;
import {default as Bdi} from "./selection/Bdi";
  selection.prototype.Bdi = Bdi;
import {default as Bdo} from "./selection/Bdo";
  selection.prototype.Bdo = Bdo;
import {default as Blockquote} from "./selection/Blockquote";
  selection.prototype.Blockquote = Blockquote;
import {default as Border} from "./selection/Border";
  selection.prototype.Border = Border;
import {default as BorderBottom} from "./selection/BorderBottom";
  selection.prototype.BorderBottom = BorderBottom;
import {default as BorderBottomColor} from "./selection/BorderBottomColor";
  selection.prototype.BorderBottomColor = BorderBottomColor;
import {default as BorderBottomLeftRadius} from "./selection/BorderBottomLeftRadius";
  selection.prototype.BorderBottomLeftRadius = BorderBottomLeftRadius;
import {default as BorderBottomRightRadius} from "./selection/BorderBottomRightRadius";
  selection.prototype.BorderBottomRightRadius = BorderBottomRightRadius;
import {default as BorderBottomStyle} from "./selection/BorderBottomStyle";
  selection.prototype.BorderBottomStyle = BorderBottomStyle;
import {default as BorderBottomWidth} from "./selection/BorderBottomWidth";
  selection.prototype.BorderBottomWidth = BorderBottomWidth;
import {default as BorderCollapse} from "./selection/BorderCollapse";
  selection.prototype.BorderCollapse = BorderCollapse;
import {default as BorderColor} from "./selection/BorderColor";
  selection.prototype.BorderColor = BorderColor;
import {default as BorderImage} from "./selection/BorderImage";
  selection.prototype.BorderImage = BorderImage;
import {default as BorderImageOutset} from "./selection/BorderImageOutset";
  selection.prototype.BorderImageOutset = BorderImageOutset;
import {default as BorderImageRepeat} from "./selection/BorderImageRepeat";
  selection.prototype.BorderImageRepeat = BorderImageRepeat;
import {default as BorderImageSlice} from "./selection/BorderImageSlice";
  selection.prototype.BorderImageSlice = BorderImageSlice;
import {default as BorderImageSource} from "./selection/BorderImageSource";
  selection.prototype.BorderImageSource = BorderImageSource;
import {default as BorderImageWidth} from "./selection/BorderImageWidth";
  selection.prototype.BorderImageWidth = BorderImageWidth;
import {default as BorderLeft} from "./selection/BorderLeft";
  selection.prototype.BorderLeft = BorderLeft;
import {default as BorderLeftColor} from "./selection/BorderLeftColor";
  selection.prototype.BorderLeftColor = BorderLeftColor;
import {default as BorderLeftStyle} from "./selection/BorderLeftStyle";
  selection.prototype.BorderLeftStyle = BorderLeftStyle;
import {default as BorderLeftWidth} from "./selection/BorderLeftWidth";
  selection.prototype.BorderLeftWidth = BorderLeftWidth;
import {default as BorderRadius} from "./selection/BorderRadius";
  selection.prototype.BorderRadius = BorderRadius;
import {default as BorderRight} from "./selection/BorderRight";
  selection.prototype.BorderRight = BorderRight;
import {default as BorderRightColor} from "./selection/BorderRightColor";
  selection.prototype.BorderRightColor = BorderRightColor;
import {default as BorderRightStyle} from "./selection/BorderRightStyle";
  selection.prototype.BorderRightStyle = BorderRightStyle;
import {default as BorderRightWidth} from "./selection/BorderRightWidth";
  selection.prototype.BorderRightWidth = BorderRightWidth;
import {default as BorderSpacing} from "./selection/BorderSpacing";
  selection.prototype.BorderSpacing = BorderSpacing;
import {default as BorderStyle} from "./selection/BorderStyle";
  selection.prototype.BorderStyle = BorderStyle;
import {default as BorderTop} from "./selection/BorderTop";
  selection.prototype.BorderTop = BorderTop;
import {default as BorderTopColor} from "./selection/BorderTopColor";
  selection.prototype.BorderTopColor = BorderTopColor;
import {default as BorderTopLeftRadius} from "./selection/BorderTopLeftRadius";
  selection.prototype.BorderTopLeftRadius = BorderTopLeftRadius;
import {default as BorderTopRightRadius} from "./selection/BorderTopRightRadius";
  selection.prototype.BorderTopRightRadius = BorderTopRightRadius;
import {default as BorderTopStyle} from "./selection/BorderTopStyle";
  selection.prototype.BorderTopStyle = BorderTopStyle;
import {default as BorderTopWidth} from "./selection/BorderTopWidth";
  selection.prototype.BorderTopWidth = BorderTopWidth;
import {default as BorderWidth} from "./selection/BorderWidth";
  selection.prototype.BorderWidth = BorderWidth;
import {default as Bottom} from "./selection/Bottom";
  selection.prototype.Bottom = Bottom;
import {default as BoxDecorationBreak} from "./selection/BoxDecorationBreak";
  selection.prototype.BoxDecorationBreak = BoxDecorationBreak;
import {default as BoxShadow} from "./selection/BoxShadow";
  selection.prototype.BoxShadow = BoxShadow;
import {default as BoxSizing} from "./selection/BoxSizing";
  selection.prototype.BoxSizing = BoxSizing;
import {default as Br} from "./selection/Br";
  selection.prototype.Br = Br;
import {default as Button} from "./selection/Button";
  selection.prototype.Button = Button;
import {default as Canvas} from "./selection/Canvas";
  selection.prototype.Canvas = Canvas;
import {default as Caption} from "./selection/Caption";
  selection.prototype.Caption = Caption;
import {default as CaptionSide} from "./selection/CaptionSide";
  selection.prototype.CaptionSide = CaptionSide;
import {default as Checkbox} from "./selection/Checkbox";
  selection.prototype.Checkbox = Checkbox;
import {default as Checked} from "./selection/Checked";
  selection.prototype.Checked = Checked;
import {default as Children} from "./selection/Children";
  selection.prototype.Children = Children;
import {default as Cite} from "./selection/Cite";
  selection.prototype.Cite = Cite;
import {default as Class} from "./selection/Class";
  selection.prototype.Class = Class;
import {default as Clear} from "./selection/Clear";
  selection.prototype.Clear = Clear;
import {default as Clip} from "./selection/Clip";
  selection.prototype.Clip = Clip;
import {default as Code} from "./selection/Code";
  selection.prototype.Code = Code;
import {default as Col} from "./selection/Col";
  selection.prototype.Col = Col;
import {default as Colgroup} from "./selection/Colgroup";
  selection.prototype.Colgroup = Colgroup;
import {default as Color} from "./selection/Color";
  selection.prototype.Color = Color;
import {default as Cols} from "./selection/Cols";
  selection.prototype.Cols = Cols;
import {default as Colspan} from "./selection/Colspan";
  selection.prototype.Colspan = Colspan;
import {default as Content} from "./selection/Content";
  selection.prototype.Content = Content;
import {default as ContentEditable} from "./selection/ContentEditable";
  selection.prototype.ContentEditable = ContentEditable;
import {default as Cursor} from "./selection/Cursor";
  selection.prototype.Cursor = Cursor;
import {default as Data} from "./selection/Data";
  selection.prototype.Data = Data;
import {default as Datalist} from "./selection/Datalist";
  selection.prototype.Datalist = Datalist;
import {default as Date} from "./selection/Date";
  selection.prototype.Date = Date;
import {default as DatetimeLocal} from "./selection/DatetimeLocal";
  selection.prototype.DatetimeLocal = DatetimeLocal;
import {default as Dd} from "./selection/Dd";
  selection.prototype.Dd = Dd;
import {default as Del} from "./selection/Del";
  selection.prototype.Del = Del;
import {default as Details} from "./selection/Details";
  selection.prototype.Details = Details;
import {default as Dfn} from "./selection/Dfn";
  selection.prototype.Dfn = Dfn;
import {default as Disabled} from "./selection/Disabled";
  selection.prototype.Disabled = Disabled;
import {default as Display} from "./selection/Display";
  selection.prototype.Display = Display;
import {default as Div} from "./selection/Div";
  selection.prototype.Div = Div;
import {default as Dl} from "./selection/Dl";
  selection.prototype.Dl = Dl;
import {default as Download} from "./selection/Download";
  selection.prototype.Download = Download;
import {default as Draggable} from "./selection/Draggable";
  selection.prototype.Draggable = Draggable;
import {default as Dropzone} from "./selection/Dropzone";
  selection.prototype.Dropzone = Dropzone;
import {default as Dt} from "./selection/Dt";
  selection.prototype.Dt = Dt;
import {default as Element} from "./selection/Element";
  selection.prototype.Element = Element;
import {default as Em} from "./selection/Em";
  selection.prototype.Em = Em;
import {default as Email} from "./selection/Email";
  selection.prototype.Email = Email;
import {default as Embed} from "./selection/Embed";
  selection.prototype.Embed = Embed;
import {default as EmptyCells} from "./selection/EmptyCells";
  selection.prototype.EmptyCells = EmptyCells;
import {default as Enctype} from "./selection/Enctype";
  selection.prototype.Enctype = Enctype;
import {default as Fieldset} from "./selection/Fieldset";
  selection.prototype.Fieldset = Fieldset;
import {default as Figcaption} from "./selection/Figcaption";
  selection.prototype.Figcaption = Figcaption;
import {default as Figure} from "./selection/Figure";
  selection.prototype.Figure = Figure;
import {default as File} from "./selection/File";
  selection.prototype.File = File;
import {default as Flex} from "./selection/Flex";
  selection.prototype.Flex = Flex;
import {default as FlexBasis} from "./selection/FlexBasis";
  selection.prototype.FlexBasis = FlexBasis;
import {default as FlexDirection} from "./selection/FlexDirection";
  selection.prototype.FlexDirection = FlexDirection;
import {default as FlexFlow} from "./selection/FlexFlow";
  selection.prototype.FlexFlow = FlexFlow;
import {default as FlexGrow} from "./selection/FlexGrow";
  selection.prototype.FlexGrow = FlexGrow;
import {default as FlexShrink} from "./selection/FlexShrink";
  selection.prototype.FlexShrink = FlexShrink;
import {default as FlexWrap} from "./selection/FlexWrap";
  selection.prototype.FlexWrap = FlexWrap;
import {default as Float} from "./selection/Float";
  selection.prototype.Float = Float;
import {default as Font} from "./selection/Font";
  selection.prototype.Font = Font;
import {default as FontFamily} from "./selection/FontFamily";
  selection.prototype.FontFamily = FontFamily;
import {default as FontFeatureSettings} from "./selection/FontFeatureSettings";
  selection.prototype.FontFeatureSettings = FontFeatureSettings;
import {default as FontKerning} from "./selection/FontKerning";
  selection.prototype.FontKerning = FontKerning;
import {default as FontLanguageOverride} from "./selection/FontLanguageOverride";
  selection.prototype.FontLanguageOverride = FontLanguageOverride;
import {default as FontSize} from "./selection/FontSize";
  selection.prototype.FontSize = FontSize;
import {default as FontSizeAdjust} from "./selection/FontSizeAdjust";
  selection.prototype.FontSizeAdjust = FontSizeAdjust;
import {default as FontStretch} from "./selection/FontStretch";
  selection.prototype.FontStretch = FontStretch;
import {default as FontStyle} from "./selection/FontStyle";
  selection.prototype.FontStyle = FontStyle;
import {default as FontSynthesis} from "./selection/FontSynthesis";
  selection.prototype.FontSynthesis = FontSynthesis;
import {default as FontVariant} from "./selection/FontVariant";
  selection.prototype.FontVariant = FontVariant;
import {default as FontVariantAlternates} from "./selection/FontVariantAlternates";
  selection.prototype.FontVariantAlternates = FontVariantAlternates;
import {default as FontVariantCaps} from "./selection/FontVariantCaps";
  selection.prototype.FontVariantCaps = FontVariantCaps;
import {default as FontVariantEastAsian} from "./selection/FontVariantEastAsian";
  selection.prototype.FontVariantEastAsian = FontVariantEastAsian;
import {default as FontVariantLigatures} from "./selection/FontVariantLigatures";
  selection.prototype.FontVariantLigatures = FontVariantLigatures;
import {default as FontVariantNumeric} from "./selection/FontVariantNumeric";
  selection.prototype.FontVariantNumeric = FontVariantNumeric;
import {default as FontVariantPosition} from "./selection/FontVariantPosition";
  selection.prototype.FontVariantPosition = FontVariantPosition;
import {default as FontWeight} from "./selection/FontWeight";
  selection.prototype.FontWeight = FontWeight;
import {default as Footer} from "./selection/Footer";
  selection.prototype.Footer = Footer;
import {default as For} from "./selection/For";
  selection.prototype.For = For;
import {default as Form} from "./selection/Form";
  selection.prototype.Form = Form;
import {default as Formaction} from "./selection/Formaction";
  selection.prototype.Formaction = Formaction;
import {default as H1} from "./selection/H1";
  selection.prototype.H1 = H1;
import {default as H2} from "./selection/H2";
  selection.prototype.H2 = H2;
import {default as H3} from "./selection/H3";
  selection.prototype.H3 = H3;
import {default as H4} from "./selection/H4";
  selection.prototype.H4 = H4;
import {default as H5} from "./selection/H5";
  selection.prototype.H5 = H5;
import {default as H6} from "./selection/H6";
  selection.prototype.H6 = H6;
import {default as HangingPunctuation} from "./selection/HangingPunctuation";
  selection.prototype.HangingPunctuation = HangingPunctuation;
import {default as HashStateRouter} from "./selection/HashStateRouter";
  selection.prototype.HashStateRouter = HashStateRouter;
import {default as Header} from "./selection/Header";
  selection.prototype.Header = Header;
import {default as Height} from "./selection/Height";
  selection.prototype.Height = Height;
import {default as Hidden} from "./selection/Hidden";
  selection.prototype.Hidden = Hidden;
import {default as Hr} from "./selection/Hr";
  selection.prototype.Hr = Hr;
import {default as Href} from "./selection/Href";
  selection.prototype.Href = Href;
import {default as Hyphens} from "./selection/Hyphens";
  selection.prototype.Hyphens = Hyphens;
import {default as I} from "./selection/I";
  selection.prototype.I = I;
import {default as Id} from "./selection/Id";
  selection.prototype.Id = Id;
import {default as Iframe} from "./selection/Iframe";
  selection.prototype.Iframe = Iframe;
import {default as Image} from "./selection/Image";
  selection.prototype.Image = Image;
import {default as ImeMode} from "./selection/ImeMode";
  selection.prototype.ImeMode = ImeMode;
import {default as Img} from "./selection/Img";
  selection.prototype.Img = Img;
import {default as Input} from "./selection/Input";
  selection.prototype.Input = Input;
import {default as InputCheckbox} from "./selection/InputCheckbox";
  selection.prototype.InputCheckbox = InputCheckbox;
import {default as InputColor} from "./selection/InputColor";
  selection.prototype.InputColor = InputColor;
import {default as InputDate} from "./selection/InputDate";
  selection.prototype.InputDate = InputDate;
import {default as InputDatetimeLocal} from "./selection/InputDatetimeLocal";
  selection.prototype.InputDatetimeLocal = InputDatetimeLocal;
import {default as InputEmail} from "./selection/InputEmail";
  selection.prototype.InputEmail = InputEmail;
import {default as InputFile} from "./selection/InputFile";
  selection.prototype.InputFile = InputFile;
import {default as InputHidden} from "./selection/InputHidden";
  selection.prototype.InputHidden = InputHidden;
import {default as InputImage} from "./selection/InputImage";
  selection.prototype.InputImage = InputImage;
import {default as InputMonth} from "./selection/InputMonth";
  selection.prototype.InputMonth = InputMonth;
import {default as InputNumber} from "./selection/InputNumber";
  selection.prototype.InputNumber = InputNumber;
import {default as InputPassword} from "./selection/InputPassword";
  selection.prototype.InputPassword = InputPassword;
import {default as InputRadio} from "./selection/InputRadio";
  selection.prototype.InputRadio = InputRadio;
import {default as InputRange} from "./selection/InputRange";
  selection.prototype.InputRange = InputRange;
import {default as InputReset} from "./selection/InputReset";
  selection.prototype.InputReset = InputReset;
import {default as InputSearch} from "./selection/InputSearch";
  selection.prototype.InputSearch = InputSearch;
import {default as InputSubmit} from "./selection/InputSubmit";
  selection.prototype.InputSubmit = InputSubmit;
import {default as InputTel} from "./selection/InputTel";
  selection.prototype.InputTel = InputTel;
import {default as InputText} from "./selection/InputText";
  selection.prototype.InputText = InputText;
import {default as InputTime} from "./selection/InputTime";
  selection.prototype.InputTime = InputTime;
import {default as InputUrl} from "./selection/InputUrl";
  selection.prototype.InputUrl = InputUrl;
import {default as InputWeek} from "./selection/InputWeek";
  selection.prototype.InputWeek = InputWeek;
import {default as Ins} from "./selection/Ins";
  selection.prototype.Ins = Ins;
import {default as JustifyContent} from "./selection/JustifyContent";
  selection.prototype.JustifyContent = JustifyContent;
import {default as Kbd} from "./selection/Kbd";
  selection.prototype.Kbd = Kbd;
import {default as Label} from "./selection/Label";
  selection.prototype.Label = Label;
import {default as Left} from "./selection/Left";
  selection.prototype.Left = Left;
import {default as Legend} from "./selection/Legend";
  selection.prototype.Legend = Legend;
import {default as LetterSpacing} from "./selection/LetterSpacing";
  selection.prototype.LetterSpacing = LetterSpacing;
import {default as Li} from "./selection/Li";
  selection.prototype.Li = Li;
import {default as LineBreak} from "./selection/LineBreak";
  selection.prototype.LineBreak = LineBreak;
import {default as LineHeight} from "./selection/LineHeight";
  selection.prototype.LineHeight = LineHeight;
import {default as Link} from "./selection/Link";
  selection.prototype.Link = Link;
import {default as Main} from "./selection/Main";
  selection.prototype.Main = Main;
import {default as Map} from "./selection/Map";
  selection.prototype.Map = Map;
import {default as Margin} from "./selection/Margin";
  selection.prototype.Margin = Margin;
import {default as MarginBottom} from "./selection/MarginBottom";
  selection.prototype.MarginBottom = MarginBottom;
import {default as MarginLeft} from "./selection/MarginLeft";
  selection.prototype.MarginLeft = MarginLeft;
import {default as MarginRight} from "./selection/MarginRight";
  selection.prototype.MarginRight = MarginRight;
import {default as MarginTop} from "./selection/MarginTop";
  selection.prototype.MarginTop = MarginTop;
import {default as Mark} from "./selection/Mark";
  selection.prototype.Mark = Mark;
import {default as MaxHeight} from "./selection/MaxHeight";
  selection.prototype.MaxHeight = MaxHeight;
import {default as MaxWidth} from "./selection/MaxWidth";
  selection.prototype.MaxWidth = MaxWidth;
import {default as Media} from "./selection/Media";
  selection.prototype.Media = Media;
import {default as Meta} from "./selection/Meta";
  selection.prototype.Meta = Meta;
import {default as Meter} from "./selection/Meter";
  selection.prototype.Meter = Meter;
import {default as Method} from "./selection/Method";
  selection.prototype.Method = Method;
import {default as MinHeight} from "./selection/MinHeight";
  selection.prototype.MinHeight = MinHeight;
import {default as MinWidth} from "./selection/MinWidth";
  selection.prototype.MinWidth = MinWidth;
import {default as Month} from "./selection/Month";
  selection.prototype.Month = Month;
import {default as Name} from "./selection/Name";
  selection.prototype.Name = Name;
import {default as Nav} from "./selection/Nav";
  selection.prototype.Nav = Nav;
import {default as NavDown} from "./selection/NavDown";
  selection.prototype.NavDown = NavDown;
import {default as NavIndex} from "./selection/NavIndex";
  selection.prototype.NavIndex = NavIndex;
import {default as NavLeft} from "./selection/NavLeft";
  selection.prototype.NavLeft = NavLeft;
import {default as NavRight} from "./selection/NavRight";
  selection.prototype.NavRight = NavRight;
import {default as NavUp} from "./selection/NavUp";
  selection.prototype.NavUp = NavUp;
import {default as Noframes} from "./selection/Noframes";
  selection.prototype.Noframes = Noframes;
import {default as Noscript} from "./selection/Noscript";
  selection.prototype.Noscript = Noscript;
import {default as Number} from "./selection/Number";
  selection.prototype.Number = Number;
import {default as Object} from "./selection/Object";
  selection.prototype.Object = Object;
import {default as Ol} from "./selection/Ol";
  selection.prototype.Ol = Ol;
import {default as OnAbort} from "./selection/OnAbort";
  selection.prototype.OnAbort = OnAbort;
import {default as OnAfterprint} from "./selection/OnAfterprint";
  selection.prototype.OnAfterprint = OnAfterprint;
import {default as OnBeforeprint} from "./selection/OnBeforeprint";
  selection.prototype.OnBeforeprint = OnBeforeprint;
import {default as OnBeforeunload} from "./selection/OnBeforeunload";
  selection.prototype.OnBeforeunload = OnBeforeunload;
import {default as OnBlur} from "./selection/OnBlur";
  selection.prototype.OnBlur = OnBlur;
import {default as OnCanplay} from "./selection/OnCanplay";
  selection.prototype.OnCanplay = OnCanplay;
import {default as OnCanplaythrough} from "./selection/OnCanplaythrough";
  selection.prototype.OnCanplaythrough = OnCanplaythrough;
import {default as OnChange} from "./selection/OnChange";
  selection.prototype.OnChange = OnChange;
import {default as OnClick} from "./selection/OnClick";
  selection.prototype.OnClick = OnClick;
import {default as OnContextmenu} from "./selection/OnContextmenu";
  selection.prototype.OnContextmenu = OnContextmenu;
import {default as OnCopy} from "./selection/OnCopy";
  selection.prototype.OnCopy = OnCopy;
import {default as OnCuechange} from "./selection/OnCuechange";
  selection.prototype.OnCuechange = OnCuechange;
import {default as OnCut} from "./selection/OnCut";
  selection.prototype.OnCut = OnCut;
import {default as OnDblclick} from "./selection/OnDblclick";
  selection.prototype.OnDblclick = OnDblclick;
import {default as OnDrag} from "./selection/OnDrag";
  selection.prototype.OnDrag = OnDrag;
import {default as OnDragend} from "./selection/OnDragend";
  selection.prototype.OnDragend = OnDragend;
import {default as OnDragenter} from "./selection/OnDragenter";
  selection.prototype.OnDragenter = OnDragenter;
import {default as OnDragleave} from "./selection/OnDragleave";
  selection.prototype.OnDragleave = OnDragleave;
import {default as OnDragover} from "./selection/OnDragover";
  selection.prototype.OnDragover = OnDragover;
import {default as OnDragstart} from "./selection/OnDragstart";
  selection.prototype.OnDragstart = OnDragstart;
import {default as OnDrop} from "./selection/OnDrop";
  selection.prototype.OnDrop = OnDrop;
import {default as OnDurationchange} from "./selection/OnDurationchange";
  selection.prototype.OnDurationchange = OnDurationchange;
import {default as OnEmptied} from "./selection/OnEmptied";
  selection.prototype.OnEmptied = OnEmptied;
import {default as OnEnded} from "./selection/OnEnded";
  selection.prototype.OnEnded = OnEnded;
import {default as OnError} from "./selection/OnError";
  selection.prototype.OnError = OnError;
import {default as OnFocus} from "./selection/OnFocus";
  selection.prototype.OnFocus = OnFocus;
import {default as OnHashchange} from "./selection/OnHashchange";
  selection.prototype.OnHashchange = OnHashchange;
import {default as OnInput} from "./selection/OnInput";
  selection.prototype.OnInput = OnInput;
import {default as OnInvalid} from "./selection/OnInvalid";
  selection.prototype.OnInvalid = OnInvalid;
import {default as OnKeydown} from "./selection/OnKeydown";
  selection.prototype.OnKeydown = OnKeydown;
import {default as OnKeypress} from "./selection/OnKeypress";
  selection.prototype.OnKeypress = OnKeypress;
import {default as OnKeyup} from "./selection/OnKeyup";
  selection.prototype.OnKeyup = OnKeyup;
import {default as OnLoad} from "./selection/OnLoad";
  selection.prototype.OnLoad = OnLoad;
import {default as OnLoadeddata} from "./selection/OnLoadeddata";
  selection.prototype.OnLoadeddata = OnLoadeddata;
import {default as OnLoadedmetadata} from "./selection/OnLoadedmetadata";
  selection.prototype.OnLoadedmetadata = OnLoadedmetadata;
import {default as OnLoadstart} from "./selection/OnLoadstart";
  selection.prototype.OnLoadstart = OnLoadstart;
import {default as OnMessage} from "./selection/OnMessage";
  selection.prototype.OnMessage = OnMessage;
import {default as OnMousedown} from "./selection/OnMousedown";
  selection.prototype.OnMousedown = OnMousedown;
import {default as OnMousemove} from "./selection/OnMousemove";
  selection.prototype.OnMousemove = OnMousemove;
import {default as OnMouseout} from "./selection/OnMouseout";
  selection.prototype.OnMouseout = OnMouseout;
import {default as OnMouseover} from "./selection/OnMouseover";
  selection.prototype.OnMouseover = OnMouseover;
import {default as OnMouseup} from "./selection/OnMouseup";
  selection.prototype.OnMouseup = OnMouseup;
import {default as OnMousewheel} from "./selection/OnMousewheel";
  selection.prototype.OnMousewheel = OnMousewheel;
import {default as OnOffline} from "./selection/OnOffline";
  selection.prototype.OnOffline = OnOffline;
import {default as OnOnline} from "./selection/OnOnline";
  selection.prototype.OnOnline = OnOnline;
import {default as OnPagehide} from "./selection/OnPagehide";
  selection.prototype.OnPagehide = OnPagehide;
import {default as OnPageshow} from "./selection/OnPageshow";
  selection.prototype.OnPageshow = OnPageshow;
import {default as OnPaste} from "./selection/OnPaste";
  selection.prototype.OnPaste = OnPaste;
import {default as OnPause} from "./selection/OnPause";
  selection.prototype.OnPause = OnPause;
import {default as OnPlay} from "./selection/OnPlay";
  selection.prototype.OnPlay = OnPlay;
import {default as OnPlaying} from "./selection/OnPlaying";
  selection.prototype.OnPlaying = OnPlaying;
import {default as OnPopstate} from "./selection/OnPopstate";
  selection.prototype.OnPopstate = OnPopstate;
import {default as OnProgress} from "./selection/OnProgress";
  selection.prototype.OnProgress = OnProgress;
import {default as OnRatechange} from "./selection/OnRatechange";
  selection.prototype.OnRatechange = OnRatechange;
import {default as OnReset} from "./selection/OnReset";
  selection.prototype.OnReset = OnReset;
import {default as OnResize} from "./selection/OnResize";
  selection.prototype.OnResize = OnResize;
import {default as OnScroll} from "./selection/OnScroll";
  selection.prototype.OnScroll = OnScroll;
import {default as OnSearch} from "./selection/OnSearch";
  selection.prototype.OnSearch = OnSearch;
import {default as OnSeeked} from "./selection/OnSeeked";
  selection.prototype.OnSeeked = OnSeeked;
import {default as OnSeeking} from "./selection/OnSeeking";
  selection.prototype.OnSeeking = OnSeeking;
import {default as OnSelect} from "./selection/OnSelect";
  selection.prototype.OnSelect = OnSelect;
import {default as OnShow} from "./selection/OnShow";
  selection.prototype.OnShow = OnShow;
import {default as OnStalled} from "./selection/OnStalled";
  selection.prototype.OnStalled = OnStalled;
import {default as OnStorage} from "./selection/OnStorage";
  selection.prototype.OnStorage = OnStorage;
import {default as OnSubmit} from "./selection/OnSubmit";
  selection.prototype.OnSubmit = OnSubmit;
import {default as OnSuspend} from "./selection/OnSuspend";
  selection.prototype.OnSuspend = OnSuspend;
import {default as OnTimeupdate} from "./selection/OnTimeupdate";
  selection.prototype.OnTimeupdate = OnTimeupdate;
import {default as OnToggle} from "./selection/OnToggle";
  selection.prototype.OnToggle = OnToggle;
import {default as OnUnload} from "./selection/OnUnload";
  selection.prototype.OnUnload = OnUnload;
import {default as OnVolumechange} from "./selection/OnVolumechange";
  selection.prototype.OnVolumechange = OnVolumechange;
import {default as OnWaiting} from "./selection/OnWaiting";
  selection.prototype.OnWaiting = OnWaiting;
import {default as OnWheel} from "./selection/OnWheel";
  selection.prototype.OnWheel = OnWheel;
import {default as Optgroup} from "./selection/Optgroup";
  selection.prototype.Optgroup = Optgroup;
import {default as Option} from "./selection/Option";
  selection.prototype.Option = Option;
import {default as Options} from "./selection/Options";
  selection.prototype.Options = Options;
import {default as Order} from "./selection/Order";
  selection.prototype.Order = Order;
import {default as Outline} from "./selection/Outline";
  selection.prototype.Outline = Outline;
import {default as OutlineColor} from "./selection/OutlineColor";
  selection.prototype.OutlineColor = OutlineColor;
import {default as OutlineOffset} from "./selection/OutlineOffset";
  selection.prototype.OutlineOffset = OutlineOffset;
import {default as OutlineStyle} from "./selection/OutlineStyle";
  selection.prototype.OutlineStyle = OutlineStyle;
import {default as OutlineWidth} from "./selection/OutlineWidth";
  selection.prototype.OutlineWidth = OutlineWidth;
import {default as Output} from "./selection/Output";
  selection.prototype.Output = Output;
import {default as Overflow} from "./selection/Overflow";
  selection.prototype.Overflow = Overflow;
import {default as OverflowWrap} from "./selection/OverflowWrap";
  selection.prototype.OverflowWrap = OverflowWrap;
import {default as OverflowX} from "./selection/OverflowX";
  selection.prototype.OverflowX = OverflowX;
import {default as OverflowY} from "./selection/OverflowY";
  selection.prototype.OverflowY = OverflowY;
import {default as P} from "./selection/P";
  selection.prototype.P = P;
import {default as Padding} from "./selection/Padding";
  selection.prototype.Padding = Padding;
import {default as PaddingBottom} from "./selection/PaddingBottom";
  selection.prototype.PaddingBottom = PaddingBottom;
import {default as PaddingLeft} from "./selection/PaddingLeft";
  selection.prototype.PaddingLeft = PaddingLeft;
import {default as PaddingRight} from "./selection/PaddingRight";
  selection.prototype.PaddingRight = PaddingRight;
import {default as PaddingTop} from "./selection/PaddingTop";
  selection.prototype.PaddingTop = PaddingTop;
import {default as Param} from "./selection/Param";
  selection.prototype.Param = Param;
import {default as ParentNode} from "./selection/ParentNode";
  selection.prototype.ParentNode = ParentNode;
import {default as Password} from "./selection/Password";
  selection.prototype.Password = Password;
import {default as Pattern} from "./selection/Pattern";
  selection.prototype.Pattern = Pattern;
import {default as Placeholder} from "./selection/Placeholder";
  selection.prototype.Placeholder = Placeholder;
import {default as Position} from "./selection/Position";
  selection.prototype.Position = Position;
import {default as Pre} from "./selection/Pre";
  selection.prototype.Pre = Pre;
import {default as Progress} from "./selection/Progress";
  selection.prototype.Progress = Progress;
import {default as Q} from "./selection/Q";
  selection.prototype.Q = Q;
import {default as Radio} from "./selection/Radio";
  selection.prototype.Radio = Radio;
import {default as Range} from "./selection/Range";
  selection.prototype.Range = Range;
import {default as Reset} from "./selection/Reset";
  selection.prototype.Reset = Reset;
import {default as Resize} from "./selection/Resize";
  selection.prototype.Resize = Resize;
import {default as Right} from "./selection/Right";
  selection.prototype.Right = Right;
import {default as Rowspan} from "./selection/Rowspan";
  selection.prototype.Rowspan = Rowspan;
import {default as Rp} from "./selection/Rp";
  selection.prototype.Rp = Rp;
import {default as Rt} from "./selection/Rt";
  selection.prototype.Rt = Rt;
import {default as Rtc} from "./selection/Rtc";
  selection.prototype.Rtc = Rtc;
import {default as Ruby} from "./selection/Ruby";
  selection.prototype.Ruby = Ruby;
import {default as S} from "./selection/S";
  selection.prototype.S = S;
import {default as Samp} from "./selection/Samp";
  selection.prototype.Samp = Samp;
import {default as Script} from "./selection/Script";
  selection.prototype.Script = Script;
import {default as Search} from "./selection/Search";
  selection.prototype.Search = Search;
import {default as Section} from "./selection/Section";
  selection.prototype.Section = Section;
import {default as Select} from "./selection/Select";
  selection.prototype.Select = Select;
import {default as Selected} from "./selection/Selected";
  selection.prototype.Selected = Selected;
import {default as Shadow} from "./selection/Shadow";
  selection.prototype.Shadow = Shadow;
import {default as Small} from "./selection/Small";
  selection.prototype.Small = Small;
import {default as Source} from "./selection/Source";
  selection.prototype.Source = Source;
import {default as Span} from "./selection/Span";
  selection.prototype.Span = Span;
import {default as Src} from "./selection/Src";
  selection.prototype.Src = Src;
import {default as Strong} from "./selection/Strong";
  selection.prototype.Strong = Strong;
import {default as Sub} from "./selection/Sub";
  selection.prototype.Sub = Sub;
import {default as Submit} from "./selection/Submit";
  selection.prototype.Submit = Submit;
import {default as Summary} from "./selection/Summary";
  selection.prototype.Summary = Summary;
import {default as Sup} from "./selection/Sup";
  selection.prototype.Sup = Sup;
import {default as Svg} from "./selection/Svg";
  selection.prototype.Svg = Svg;
import {default as TabSize} from "./selection/TabSize";
  selection.prototype.TabSize = TabSize;
import {default as Tabindex} from "./selection/Tabindex";
  selection.prototype.Tabindex = Tabindex;
import {default as Table} from "./selection/Table";
  selection.prototype.Table = Table;
import {default as TableLayout} from "./selection/TableLayout";
  selection.prototype.TableLayout = TableLayout;
import {default as Target} from "./selection/Target";
  selection.prototype.Target = Target;
import {default as Tbody} from "./selection/Tbody";
  selection.prototype.Tbody = Tbody;
import {default as Td} from "./selection/Td";
  selection.prototype.Td = Td;
import {default as Tel} from "./selection/Tel";
  selection.prototype.Tel = Tel;
import {default as Template} from "./selection/Template";
  selection.prototype.Template = Template;
import {default as Text} from "./selection/Text";
  selection.prototype.Text = Text;
import {default as TextAlign} from "./selection/TextAlign";
  selection.prototype.TextAlign = TextAlign;
import {default as TextAlignLast} from "./selection/TextAlignLast";
  selection.prototype.TextAlignLast = TextAlignLast;
import {default as TextCombineUpright} from "./selection/TextCombineUpright";
  selection.prototype.TextCombineUpright = TextCombineUpright;
import {default as TextDecoration} from "./selection/TextDecoration";
  selection.prototype.TextDecoration = TextDecoration;
import {default as TextDecorationColor} from "./selection/TextDecorationColor";
  selection.prototype.TextDecorationColor = TextDecorationColor;
import {default as TextDecorationLine} from "./selection/TextDecorationLine";
  selection.prototype.TextDecorationLine = TextDecorationLine;
import {default as TextDecorationStyle} from "./selection/TextDecorationStyle";
  selection.prototype.TextDecorationStyle = TextDecorationStyle;
import {default as TextIndent} from "./selection/TextIndent";
  selection.prototype.TextIndent = TextIndent;
import {default as TextJustify} from "./selection/TextJustify";
  selection.prototype.TextJustify = TextJustify;
import {default as TextOverflow} from "./selection/TextOverflow";
  selection.prototype.TextOverflow = TextOverflow;
import {default as TextShadow} from "./selection/TextShadow";
  selection.prototype.TextShadow = TextShadow;
import {default as TextTransform} from "./selection/TextTransform";
  selection.prototype.TextTransform = TextTransform;
import {default as TextUnderlinePosition} from "./selection/TextUnderlinePosition";
  selection.prototype.TextUnderlinePosition = TextUnderlinePosition;
import {default as Textarea} from "./selection/Textarea";
  selection.prototype.Textarea = Textarea;
import {default as Tfoot} from "./selection/Tfoot";
  selection.prototype.Tfoot = Tfoot;
import {default as Th} from "./selection/Th";
  selection.prototype.Th = Th;
import {default as Thead} from "./selection/Thead";
  selection.prototype.Thead = Thead;
import {default as Time} from "./selection/Time";
  selection.prototype.Time = Time;
import {default as Title} from "./selection/Title";
  selection.prototype.Title = Title;
import {default as Top} from "./selection/Top";
  selection.prototype.Top = Top;
import {default as Tr} from "./selection/Tr";
  selection.prototype.Tr = Tr;
import {default as Track} from "./selection/Track";
  selection.prototype.Track = Track;
import {default as U} from "./selection/U";
  selection.prototype.U = U;
import {default as Ul} from "./selection/Ul";
  selection.prototype.Ul = Ul;
import {default as Url} from "./selection/Url";
  selection.prototype.Url = Url;
import {default as UserSelect} from "./selection/UserSelect";
  selection.prototype.UserSelect = UserSelect;
import {default as Validity} from "./selection/Validity";
  selection.prototype.Validity = Validity;
import {default as Value} from "./selection/Value";
  selection.prototype.Value = Value;
import {default as Var} from "./selection/Var";
  selection.prototype.Var = Var;
import {default as VerticalAlign} from "./selection/VerticalAlign";
  selection.prototype.VerticalAlign = VerticalAlign;
import {default as Video} from "./selection/Video";
  selection.prototype.Video = Video;
import {default as Visibility} from "./selection/Visibility";
  selection.prototype.Visibility = Visibility;
import {default as Wbr} from "./selection/Wbr";
  selection.prototype.Wbr = Wbr;
import {default as Week} from "./selection/Week";
  selection.prototype.Week = Week;
import {default as WhiteSpace} from "./selection/WhiteSpace";
  selection.prototype.WhiteSpace = WhiteSpace;
import {default as Width} from "./selection/Width";
  selection.prototype.Width = Width;
import {default as WordBreak} from "./selection/WordBreak";
  selection.prototype.WordBreak = WordBreak;
import {default as WordSpacing} from "./selection/WordSpacing";
  selection.prototype.WordSpacing = WordSpacing;
import {default as WordWrap} from "./selection/WordWrap";
  selection.prototype.WordWrap = WordWrap;
import {default as ZIndex} from "./selection/ZIndex";
  selection.prototype.ZIndex = ZIndex;
import {default as clear} from "./selection/clear";
  selection.prototype.clear = clear;
